[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/google/gopacket"
  revision = "1a2aa715ae412f434ae0bbb833442d14880cab8a"

[[constraint]]
  name = "github.com/broderickhyman/photon_spectator"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "3536a929edddb9a5b34bd6861dc4a9647cb459fe"

[[constraint]]
  name = "github.com/broderickhyman/go-githubupdate"
  branch = "master"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/getlantern/systray"
  revision = "0daad7b8e5bd9533578e674141123f6a264a7454"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.1.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"
