[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/google/gopacket"
  revision = "8af772c0bcc826f671fd7c133917fec9686d720d"

[[constraint]]
  name = "github.com/hmadison/photon_spectator"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/albiondata/go-githubupdate"
  version = "0.0.3"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  source = "https://github.com/gradiuscypher/gopsutil.git"
  revision = "d573c8e3f1c5337585b0e285214e80df7429d8b5"

[[constraint]]
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/getlantern/systray"
